# Fichier de configuration jekyll
author :
  name : Pierre Guéguin
  email : pgueguin2@gmail.com
lsi : true
permalink: date
production_url : http://pierre.gueguin.net
pygments: true
title : Pierre Guéguin page
  
