# Fichier de configuration jekyll
author :
  name : Pierre Guéguin
  email : pgueguin2@gmail.com
  avatar : /img/avatar/09.jpg
  openid : http://openid.claimid.com/pgueguin
lsi : true
permalink: date
production_url : http://pierre.gueguin.net
pygments: true
title : Pierre Guéguin page
  
